/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Buscador;
import java.io.File;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author md
 */
public class VistaT extends javax.swing.JFrame {

    String sistema;
    private Buscador b = new Buscador("");
    private javax.swing.table.DefaultTableModel custom;
    TableRowSorter filtro;
    RowFilter f;
    /**
     * Creates new form VistaT
     */
    public VistaT() {
        initComponents();

        custom = new DefaultTableModel(new Object[][]{}, new String[]{"Nombre", "Extension", "Tamaño", "F/D"});
        jTable1.setModel(custom);
        sistema = System.getProperty("os.name");
       
        filtro = new TableRowSorter(custom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bBuscar = new javax.swing.JButton();
        bBuscarExtension = new javax.swing.JButton();
        jtxtDirectorio = new javax.swing.JTextField();
        jtxtExtension = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSalida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduce una direccion");

        jLabel2.setText("Extension");

        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/foldergreenjava_93025.png"))); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bBuscarExtension.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/1485481218-50_78644.png"))); // NOI18N
        bBuscarExtension.setText("Buscar por extension");
        bBuscarExtension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarExtensionActionPerformed(evt);
            }
        });

        jtxtDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDirectorioActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtSalida.setEditable(false);
        txtSalida.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bBuscarExtension))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBuscar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBuscarExtension)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(6, 6, 6)
                .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    
    
    
    
    
    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        buscar();

    }//GEN-LAST:event_bBuscarActionPerformed

    private void bBuscarExtensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarExtensionActionPerformed
        jTable1.setRowSorter(filtro);
        String extension = jtxtExtension.getText();
        if(extension.length()==0){
            filtro.setRowFilter(null);
        }else{
            filtro.setRowFilter(f.regexFilter(extension));
        }
    

    }//GEN-LAST:event_bBuscarExtensionActionPerformed

    private void jtxtDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDirectorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDirectorioActionPerformed

    public void rellenar(File[] fichero) {

        for (File fichero1 : fichero) {
            try {
                File aux = new File(fichero1.getAbsolutePath());
                String[] fila = new String[]{aux.getName(), mExtension(aux), mTamaño(aux), mTipo(aux)
                };
                custom.addRow(fila);
            } catch (NullPointerException e) {
                txtSalida.setText(e.toString());
                JOptionPane.showMessageDialog(rootPane, e);

            }
        }

    }

    public void buscar() {
        borrar();
        String dire;
        boolean correcto = true;
        if (jtxtDirectorio.getText().equals("")) {
            if (sistema.startsWith("Windows") || sistema.startsWith("Microsoft")) {
                jtxtDirectorio.setText("C:");
                dire = "C:";
                b.ponruta(dire);
            } else {
                jtxtDirectorio.setText("/home/");
                dire = "/home/";
                b.ponruta(dire);

            }
            System.out.println("dire " + dire);
            

        }
        dire =jtxtDirectorio.getText();
                
        b.ponruta(dire);
        correcto = b.Existe();
        if (correcto) {
            rellenar(b.ficheros);
            txtSalida.setText("hecho");
        } else {
            txtSalida.setText("error, no existe el directorio");
        }

    }

    public String mTamaño(File f) {
        return Long.toString(f.length()) + "bytes";
    }

    public String mTipo(File f) {
        if (f.isDirectory()) {
            return "directorio";
        } else {
            return "es un archivo";
        }
    }

    public String mExtension(File f) {
        if (f.isFile()) {
            String extension = "";
            if (f.getName().contains(".")) {
                extension = Arrays.stream(f.getName().split("\\.")).reduce((a, b) -> b).orElse(null);
            }
            return extension;
        }
        return "";
    }

   
    
    public void borrar(){
        custom.setRowCount(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaT().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bBuscarExtension;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtDirectorio;
    private javax.swing.JTextField jtxtExtension;
    private javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}
